import { ObjectID } from 'mongodb';

export interface User {
  _id: ObjectID;
  id: number;
  idstr: string;
  class: number;
  screen_name: string;
  name: string;
  province: string;
  city: string;
  location: string;
  description: string;
  url: string;
  profile_image_url: string;
  cover_image_phone: string;
  profile_url: string;
  domain: string;
  weihao: string;
  gender: string;
  followers_count: number;
  friends_count: number;
  pagefriends_count: number;
  statuses_count: number;
  video_status_count: number;
  video_play_count: number;
  favourites_count: number;
  created_at: string;
  following: boolean;
  allow_all_act_msg: boolean;
  geo_enabled: boolean;
  verified: boolean;
  verified_type: number;
  remark: string;
  email: string;
  insecurity: Insecurity;
  ptype: number;
  allow_all_comment: boolean;
  avatar_large: string;
  avatar_hd: string;
  verified_reason: string;
  verified_trade: string;
  verified_reason_url: string;
  verified_source: string;
  verified_source_url: string;
  follow_me: boolean;
  like: boolean;
  like_me: boolean;
  online_status: number;
  bi_followers_count: number;
  lang: string;
  star: number;
  mbtype: number;
  mbrank: number;
  block_word: number;
  block_app: number;
  credit_score: number;
  user_ability: number;
  urank: number;
  story_read_state: number;
  vclub_member: number;
  is_teenager: number;
  is_guardian: number;
  is_teenager_list: number;
  pc_new: number;
  special_follow: boolean;
  planet_video: number;
  video_mark: number;
  live_status: number;
  tab_manage: string;
  cardid: string;
  avatargj_id: string;
  verified_state?: number;
  verified_level?: number;
  verified_type_ext?: number;
  has_service_tel?: boolean;
  verified_reason_modified: string;
  verified_contact_name: string;
  verified_contact_email: string;
  verified_contact_mobile: string;
  cover_image: string;
  unicom_free_pc: string;
}

export interface Insecurity {
  sexual_content: boolean;
}

export type UserID = User['id'];
